const WAVE = 1;
const SUN = 2;
const GEAR = 3;
const MOON = 4;
const WIND = 5;

const PICKUP_DOLPHIN_NAME1 = '咲宮　入華(メイド水着/ドルフィンフェス)';
const PICKUP_DOLPHIN_NAME2 = '咲宮　小針(メイド水着/ドルフィンフェス)';
const PICKUP_MEMORY_NAME1 = 'メイド姉妹のお給仕タイム！(ドルフィンフェス)';

const PICKUP_DOLPHIN_TYPE1 = WIND;
const PICKUP_DOLPHIN_TYPE2 = WIND;
const PICKUP_MEMORY_TYPE1 = WIND;

export const defaultInfo = {
  weights: [
    [ 741, 0.01 ],
    [ 740, 0.01 ],
    [ 730, 0.05 ],
    [ 720, 0.4 ],
    [ 841, 0.01 ],
    [ 840, 0.02 ],
    [ 830, 0.1 ],
    [ 820, 0.4 ]
  ],
  pickup: [
    [ PICKUP_DOLPHIN_NAME1, 0.5 ],
    [ PICKUP_DOLPHIN_NAME2, 0.5 ],
    [ PICKUP_MEMORY_NAME1, 1 ]
  ]
};

export const defaultTable =  [
  { name: PICKUP_DOLPHIN_NAME1, rarity: 741, iconType: PICKUP_DOLPHIN_TYPE1 },
  { name: PICKUP_DOLPHIN_NAME2, rarity: 741, iconType: PICKUP_DOLPHIN_TYPE2 },
  { name: '咲宮　入華(水着)', rarity: 740, iconType: WAVE },
  { name: '都条　みちる(水着)', rarity: 740, iconType: WAVE },
  { name: '陽南　杏里(水着)', rarity: 740, iconType: WAVE },
  { name: '彩戸　詩絵(水着)', rarity: 740, iconType: WAVE },
  { name: '咲宮　小針(水着)', rarity: 740, iconType: SUN },
  { name: '住乃絵　紫苑(水着)', rarity: 740, iconType: WIND },
  { name: 'ヘリー・ルイス(水着)', rarity: 740, iconType: WIND },
  { name: 'ヴィーナ(水着)', rarity: 740, iconType: WIND },
  { name: 'セレナ・ルイス(水着)', rarity: 740, iconType: WIND },
  { name: '山葉　由芽(水着)', rarity: 740, iconType: SUN },
  { name: '浦見　かな(水着)', rarity: 740, iconType: SUN },
  { name: '相馬　颯(水着)', rarity: 740, iconType: MOON },
  { name: '風見　エレン(水着)', rarity: 740, iconType: MOON },
  { name: '永雪　氷織(水着)', rarity: 740, iconType: MOON },
  { name: 'シュネー・ヴァイスベルグ(水着)', rarity: 740, iconType: MOON },
  { name: '長土　萌依(水着)', rarity: 740, iconType: SUN },
  { name: '黒瀬　見波(水着)', rarity: 740, iconType: GEAR },
  { name: '伊澄　桐利(水着)', rarity: 740, iconType: GEAR },
  { name: '刃兼　乙姫(水着)', rarity: 740, iconType: GEAR },
  { name: '暮無　夕離(水着)', rarity: 740, iconType: GEAR },
  { name: '住乃絵　紫苑(WinterCollection)', rarity: 740, iconType: SUN },
  { name: 'ヴィーナ(WinterCollection)', rarity: 740, iconType: SUN },
  { name: 'ヘリー・ルイス(トナカイサンタ)', rarity: 740, iconType: SUN },
  { name: 'セレナ・ルイス(リボンサンタ)', rarity: 740, iconType: SUN },
  { name: '永雪　氷織(艶晴れ着)', rarity: 740, iconType: WAVE },
  { name: 'シュネー・ヴァイスベルグ(艶晴れ着)', rarity: 740, iconType: WAVE },
  { name: '黒瀬　見波(ブラックバニー)', rarity: 740, iconType: MOON },
  { name: '伊澄　桐利(ホワイトバニー)', rarity: 740, iconType: MOON },
  { name: '咲宮　入華(花蝶柄チャイナ)', rarity: 740, iconType: WIND },
  { name: '都条　みちる(ロングチャイナ)', rarity: 740, iconType: WIND },
  { name: '陽南　杏里(バレンタイン)', rarity: 740, iconType: GEAR },
  { name: '彩戸　詩絵(バレンタイン)', rarity: 740, iconType: GEAR },
  { name: '山葉　由芽(サキュバス)', rarity: 740, iconType: GEAR },
  { name: '浦見　かな(魔法少女・悪)', rarity: 740, iconType: GEAR },
  { name: '相馬　颯(ニーソメイド)', rarity: 740, iconType: WAVE },
  { name: '風見　エレン(ミニスカメイド)', rarity: 740, iconType: WAVE },
  { name: '刃兼　乙姫(セクシーポリス)', rarity: 740, iconType: MOON },
  { name: '暮無　夕離(セクシーポリス)', rarity: 740, iconType: MOON },
  { name: '村早　麻汐(水着)', rarity: 740, iconType: WIND },
  { name: '久々利　トモ(水着)', rarity: 740, iconType: WIND },
  { name: '陽南　杏里(セクシーセーター)', rarity: 740, iconType: WAVE },
  { name: 'ヘリー・ルイス(大きめシャツ)', rarity: 740, iconType: WAVE },
  { name: 'ヴィーナ(ウェディングビキニ)', rarity: 740, iconType: WIND },
  { name: '彩戸　詩絵(ウェディングビキニ)', rarity: 740, iconType: WIND },
  { name: '黒瀬　見波(ワンピースナース)', rarity: 740, iconType: WIND },
  { name: 'セレナ・ルイス(ミニスカナース)', rarity: 740, iconType: WIND },
  { name: '住乃絵　紫苑(シースルーセーラー)', rarity: 740, iconType: MOON },
  { name: '久々利　トモ(フリルセーラー)', rarity: 740, iconType: MOON },
  { name: '山葉　由芽(牛柄ビキニ)', rarity: 740, iconType: SUN },
  { name: '風見　エレン(ワンちゃんビキニ)', rarity: 740, iconType: SUN },
  { name: '村早　麻汐(チアリーダー)', rarity: 740, iconType: GEAR },
  { name: 'シュネー・ヴァイスベルグ(マーチングバンド)', rarity: 740, iconType: GEAR },
  { name: '永雪　氷織(女教師)', rarity: 740, iconType: WIND },
  { name: '浦見　かな(スモック)', rarity: 740, iconType: WIND },
  { name: 'アイネス(水着)', rarity: 740, iconType: GEAR },
  { name: 'ナハト(水着)', rarity: 740, iconType: GEAR },
  { name: '咲良・アントニー(水着)', rarity: 740, iconType: MOON },
  { name: 'アマデア・ウォルファ(水着)', rarity: 740, iconType: MOON },
  { name: '刃兼　乙姫(スク水シスター)', rarity: 740, iconType: WAVE },
  { name: '都条　みちる(COOLエージェント/ドルフィンフェス)', rarity: 740, iconType: GEAR },
  { name: '黒瀬　見波(ダークファンタズム/ドルフィンフェス)', rarity: 740, iconType: WIND },
  { name: 'アイネス(K16-BLUE/ドルフィンフェス)', rarity: 740, iconType: MOON },
  { name: 'ナハト(K48-PINK/ドルフィンフェス)', rarity: 740, iconType: MOON },
  { name: '咲宮　入華(サマータイムドルフィン/ドルフィンフェス)', rarity: 740, iconType: GEAR },
  { name: '彩戸　詩絵(スリットシスター/ドルフィンフェス)', rarity: 740, iconType: WAVE },
  { name: '久々利　トモ(クリスマスナイトウェア/ドルフィンフェス)', rarity: 740, iconType: WAVE },
  { name: '村早　麻汐(サンタビキニ/ドルフィンフェス)', rarity: 740, iconType: WAVE },
  { name: '住乃絵　紫苑(和羽織ビキニ/ドルフィンフェス)', rarity: 740, iconType: WIND },
  { name: '風見　エレン(2024迎春ビキニ/ドルフィンフェス)', rarity: 740, iconType: WIND },
  { name: '暮無　夕離(HMK-SP/ドルフィンフェス)', rarity: 740, iconType: SUN },
  { name: '刃兼　乙姫(HMK-MA/ドルフィンフェス)', rarity: 740, iconType: SUN },
  { name: 'ヴィーナ(Vt‐Collection Eros/ドルフィンフェス)', rarity: 740, iconType: GEAR },
  { name: 'セレナ・ルイス(Vt‐Collection Philia/ドルフィンフェス)', rarity: 740, iconType: GEAR },
  { name: '山葉　由芽(URAMI戦闘員YUME/ドルフィンフェス)', rarity: 740, iconType: SUN },
  { name: '浦見　かな(URAMI女幹部KANA/ドルフィンフェス)', rarity: 740, iconType: SUN },
  { name: '永雪　氷織(アブソリュートモンスター/ドルフィンフェス)', rarity: 740, iconType: WAVE },
  { name: 'シュネー・ヴァイスベルグ(ジーニアストレーナー/ドルフィンフェス)', rarity: 740, iconType: WAVE },
  { name: '咲良・アントニー(シークレットサービス/ドルフィンフェス)', rarity: 740, iconType: MOON },
  { name: 'アマデア・ウォルファ(エキセントリックレディ/ドルフィンフェス)', rarity: 740, iconType: MOON },
  { name: '咲宮　入華(ユニフォーム)', rarity: 730, iconType: MOON },
  { name: '都条　みちる(ユニフォーム)', rarity: 730, iconType: MOON },
  { name: '陽南　杏里(ユニフォーム)', rarity: 730, iconType: GEAR },
  { name: '彩戸　詩絵(ユニフォーム)', rarity: 730, iconType: GEAR },
  { name: '咲宮　小針(ユニフォーム)', rarity: 730, iconType: MOON },
  { name: '相馬　颯(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: '風見　エレン(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: '永雪　氷織(ユニフォーム)', rarity: 730, iconType: WAVE },
  { name: 'シュネー・ヴァイスベルグ(ユニフォーム)', rarity: 730, iconType: WAVE },
  { name: '長土　萌依(ユニフォーム)', rarity: 730, iconType: WIND },
  { name: '黒瀬　見波(ユニフォーム)', rarity: 730, iconType: WIND },
  { name: '伊澄　桐利(ユニフォーム)', rarity: 730, iconType: WIND },
  { name: '刃兼　乙姫(ユニフォーム)', rarity: 730, iconType: WAVE },
  { name: '暮無　夕離(ユニフォーム)', rarity: 730, iconType: WAVE },
  { name: '住乃絵　紫苑(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: 'ヘリー・ルイス(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: 'ヴィーナ(ユニフォーム)', rarity: 730, iconType: GEAR },
  { name: 'セレナ・ルイス(ユニフォーム)', rarity: 730, iconType: GEAR },
  { name: '山葉　由芽(ユニフォーム)', rarity: 730, iconType: WIND },
  { name: '浦見　かな(ユニフォーム)', rarity: 730, iconType: WIND },
  { name: '村早　麻汐(ユニフォーム)', rarity: 730, iconType: MOON },
  { name: '久々利　トモ(ユニフォーム)', rarity: 730, iconType: MOON },
  { name: 'アイネス(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: 'ナハト(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: '咲良・アントニー(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: 'アマデア・ウォルファ(ユニフォーム)', rarity: 730, iconType: SUN },
  { name: '咲宮　入華(私服)', rarity: 720, iconType: WIND },
  { name: '都条　みちる(私服)', rarity: 720, iconType: WIND },
  { name: '陽南　杏里(私服)', rarity: 720, iconType: SUN },
  { name: '彩戸　詩絵(私服)', rarity: 720, iconType: SUN },
  { name: '咲宮　小針(私服)', rarity: 720, iconType: SUN },
  { name: '相馬　颯(私服)', rarity: 720, iconType: WAVE },
  { name: '風見　エレン(私服)', rarity: 720, iconType: WAVE },
  { name: '永雪　氷織(私服)', rarity: 720, iconType: GEAR },
  { name: 'シュネー・ヴァイスベルグ(私服)', rarity: 720, iconType: GEAR },
  { name: '長土　萌依(私服)', rarity: 720, iconType: GEAR },
  { name: '黒瀬　見波(私服)', rarity: 720, iconType: MOON },
  { name: '伊澄　桐利(私服)', rarity: 720, iconType: MOON },
  { name: '刃兼　乙姫(私服)', rarity: 720, iconType: SUN },
  { name: '暮無　夕離(私服)', rarity: 720, iconType: SUN },
  { name: '住乃絵　紫苑(私服)', rarity: 720, iconType: WAVE },
  { name: 'ヘリー・ルイス(私服)', rarity: 720, iconType: WAVE },
  { name: 'ヴィーナ(私服)', rarity: 720, iconType: MOON },
  { name: 'セレナ・ルイス(私服)', rarity: 720, iconType: MOON },
  { name: '山葉　由芽(私服)', rarity: 720, iconType: GEAR },
  { name: '浦見　かな(私服)', rarity: 720, iconType: GEAR },
  { name: '村早　麻汐(私服)', rarity: 720, iconType: WIND },
  { name: '久々利　トモ(私服)', rarity: 720, iconType: WIND },
  { name: 'アイネス(私服)', rarity: 720, iconType: WIND },
  { name: 'ナハト(私服)', rarity: 720, iconType: WIND },
  { name: '咲良・アントニー(私服)', rarity: 720, iconType: WIND },
  { name: 'アマデア・ウォルファ(私服)', rarity: 720, iconType: WIND },
  { name: PICKUP_MEMORY_NAME1, rarity: 841, iconType: PICKUP_MEMORY_TYPE1 },
  { name: 'ワダツミを泳ぐイルカたち', rarity: 840, iconType: WAVE },
  { name: 'パートナー', rarity: 840, iconType: WAVE },
  { name: 'KAZAMIの新星', rarity: 840, iconType: MOON },
  { name: '絶対女王のパートナーとして', rarity: 840, iconType: MOON },
  { name: '祝！ 初勝利', rarity: 840, iconType: GEAR },
  { name: '立場が変わっても', rarity: 840, iconType: GEAR },
  { name: '検討と試行', rarity: 840, iconType: WIND },
  { name: '自由と感覚', rarity: 840, iconType: WIND },
  { name: '大切な愛機', rarity: 840, iconType: SUN },
  { name: 'KIRISHIMAの結束', rarity: 840, iconType: WIND },
  { name: 'WINNER KAZAMI', rarity: 840, iconType: WAVE },
  { name: '体操コミュニケーション', rarity: 840, iconType: SUN },
  { name: '提携発表会見', rarity: 840, iconType: GEAR },
  { name: '勝利？記念！', rarity: 840, iconType: SUN },
  { name: '大きな愛を！', rarity: 840, iconType: MOON },
  { name: 'かつてのライバル', rarity: 840, iconType: GEAR },
  { name: '練習試合も真剣に', rarity: 840, iconType: WIND },
  { name: '射撃理論と令嬢', rarity: 840, iconType: SUN },
  { name: '二人の愛の証', rarity: 840, iconType: MOON },
  { name: 'BREAK!!', rarity: 840, iconType: WAVE },
  { name: 'ワダツミサンゴ礁', rarity: 840, iconType: MOON },
  { name: 'スイカ割り対決', rarity: 840, iconType: WAVE },
  { name: 'ビーチフラッグ対決！', rarity: 840, iconType: GEAR },
  { name: '愛の休息', rarity: 840, iconType: GEAR },
  { name: '煌めきに導かれて', rarity: 840, iconType: SUN },
  { name: 'お預けホームパーティー', rarity: 840, iconType: SUN },
  { name: 'おもいおもいの願い', rarity: 840, iconType: WAVE },
  { name: 'カジノ「ENOMY」へようこそ！', rarity: 840, iconType: MOON },
  { name: '紫月・愛の満漢', rarity: 840, iconType: WIND },
  { name: '感謝をコーチに', rarity: 840, iconType: GEAR },
  { name: 'フレームの中の闇と星', rarity: 840, iconType: GEAR },
  { name: '勝利へのインスピレーション', rarity: 840, iconType: WAVE },
  { name: 'ワダツミ海上保安部隊', rarity: 840, iconType: MOON },
  { name: 'NEW WAVE COMIN\'', rarity: 840, iconType: WIND },
  { name: '一つのチームに', rarity: 840, iconType: MOON },
  { name: '常勝無敗への挑戦', rarity: 840, iconType: SUN },
  { name: 'ホップの花園', rarity: 840, iconType: WAVE },
  { name: '浜辺の女神たち', rarity: 840, iconType: WIND },
  { name: 'ドキドキ☆健康診断', rarity: 840, iconType: WAVE },
  { name: '甲板上のマジックアワー', rarity: 840, iconType: MOON },
  { name: '夢のわんわんカフェ', rarity: 840, iconType: SUN },
  { name: 'GOGO！押忍押忍！応援団', rarity: 840, iconType: GEAR },
  { name: '結成、お世話され隊！', rarity: 840, iconType: WIND },
  { name: 'HGT-OCT稼働実験', rarity: 840, iconType: GEAR },
  { name: 'ジェットバトル耐久テスト', rarity: 840, iconType: GEAR },
  { name: '特別潜入班『KIRISHIMA』(ドルフィンフェス)', rarity: 840, iconType: GEAR },
  { name: '闇に集いし者たち(ドルフィンフェス)', rarity: 840, iconType: WIND },
  { name: 'SWIM in DATA(ドルフィンフェス)', rarity: 840, iconType: MOON },
  { name: 'DIVE into DATA(ドルフィンフェス)', rarity: 840, iconType: MOON },
  { name: 'Vacation×JET BATTLE(ドルフィンフェス)', rarity: 840, iconType: GEAR },
  { name: '明日への希望の歌(ドルフィンフェス)', rarity: 840, iconType: WAVE },
  { name: 'サンタコスパーティ！(ドルフィンフェス)', rarity: 840, iconType: WAVE },
  { name: '愛の宴席(ドルフィンフェス)', rarity: 840, iconType: WIND },
  { name: '潜入ミッション開始(ドルフィンフェス)', rarity: 840, iconType: SUN },
  { name: '手作りチョコ頂上決戦!(ドルフィンフェス)', rarity: 840, iconType: GEAR },
  { name: '悪の女幹部KANA(ドルフィンフェス)', rarity: 840, iconType: SUN },
  { name: '方程式が生み出す絶対女王(ドルフィンフェス)', rarity: 840, iconType: WAVE },
  { name: '奇婦人と近衛兵(ドルフィンフェス)', rarity: 840, iconType: MOON },
  { name: 'やめられない味', rarity: 830, iconType: SUN },
  { name: 'もう一度走り出すには', rarity: 830, iconType: GEAR },
  { name: 'いつもの自慢話', rarity: 830, iconType: WIND },
  { name: '探求心は止まらない', rarity: 830, iconType: WAVE },
  { name: 'お忍びバレ', rarity: 830, iconType: MOON },
  { name: '道場の縁側にて', rarity: 830, iconType: WIND },
  { name: '運命の出会い', rarity: 830, iconType: WAVE },
  { name: '必要なものは', rarity: 830, iconType: SUN },
  { name: '思い立ったが吉日', rarity: 830, iconType: GEAR },
  { name: '結束の自撮り', rarity: 830, iconType: WIND },
  { name: '騒がしい昼食時', rarity: 830, iconType: MOON },
  { name: 'プール開きの大掃除', rarity: 830, iconType: GEAR },
  { name: '大人同士の付き合い', rarity: 830, iconType: SUN },
  { name: 'セレブリティ・パーティー', rarity: 830, iconType: WAVE },
  { name: '一人のファンとして', rarity: 830, iconType: WIND },
  { name: 'セレブの休日', rarity: 830, iconType: MOON },
  { name: '同一のコントラスト', rarity: 830, iconType: GEAR },
  { name: '氷の絶対女王vs刃兼流武術', rarity: 830, iconType: SUN },
  { name: 'それ行け！由芽号！', rarity: 830, iconType: MOON },
  { name: 'すれ違う二人', rarity: 830, iconType: WAVE },
  { name: 'シャワータイム', rarity: 830, iconType: MOON },
  { name: '脱落者一名', rarity: 830, iconType: WAVE },
  { name: '聞く耳持たず', rarity: 830, iconType: GEAR },
  { name: 'お姉ちゃん力', rarity: 830, iconType: GEAR },
  { name: '夕凪寮の雪合戦！？', rarity: 830, iconType: SUN },
  { name: '絶対的なケーキ作り', rarity: 830, iconType: SUN },
  { name: '刃兼道場かるた大会', rarity: 830, iconType: WAVE },
  { name: 'アウトサイドベット', rarity: 830, iconType: MOON },
  { name: '実は着たことアリ？', rarity: 830, iconType: WIND },
  { name: 'チョコトレンドの最先端', rarity: 830, iconType: GEAR },
  { name: '撮影会準備中', rarity: 830, iconType: GEAR },
  { name: 'メイド給仕の心得', rarity: 830, iconType: WAVE },
  { name: '取り締まり強化期間中！', rarity: 830, iconType: WIND },
  { name: 'いつものラジオ', rarity: 830, iconType: WIND },
  { name: 'ライバルに勝つために', rarity: 830, iconType: MOON },
  { name: '激闘の末に', rarity: 830, iconType: SUN },
  { name: '迫る愛の化身', rarity: 830, iconType: WAVE },
  { name: '運命を決めるブーケ', rarity: 830, iconType: WIND },
  { name: '愛のお悩み診察室', rarity: 830, iconType: WIND },
  { name: 'デッキ掃除徒競走', rarity: 830, iconType: MOON },
  { name: '命の白い水', rarity: 830, iconType: SUN },
  { name: '海津見学園マーチングバンド', rarity: 830, iconType: GEAR },
  { name: '制服も日本文化？', rarity: 830, iconType: WIND },
  { name: '定期メンテナンス中', rarity: 830, iconType: MOON },
  { name: 'サプライズゲスト登場！', rarity: 830, iconType: WAVE },
  { name: '出会いは突然に', rarity: 820, iconType: SUN },
  { name: '無知の無知', rarity: 820, iconType: WAVE },
  { name: 'アンダー・ザ・ガン', rarity: 820, iconType: GEAR },
  { name: 'お姉ちゃんの読み聞かせ', rarity: 820, iconType: MOON },
  { name: '潮風を感じて', rarity: 820, iconType: WIND },
  { name: '出かける準備', rarity: 820, iconType: SUN },
  { name: '内熱', rarity: 820, iconType: WAVE },
  { name: '子ども先生の夕方', rarity: 820, iconType: GEAR },
  { name: 'D-AR-KNIGHTS', rarity: 820, iconType: MOON },
  { name: 'マルチパッション', rarity: 820, iconType: WIND },
  { name: '鍛錬は欠かさない', rarity: 820, iconType: SUN },
  { name: '本物の感触', rarity: 820, iconType: WAVE },
  { name: '一匹狼', rarity: 820, iconType: GEAR },
  { name: '束の間の休息', rarity: 820, iconType: MOON },
  { name: '美の写像', rarity: 820, iconType: WIND },
  { name: '飽くなき探求心', rarity: 820, iconType: SUN },
  { name: 'いつものひとり晩酌', rarity: 820, iconType: WAVE },
  { name: 'お気に入りの場所', rarity: 820, iconType: GEAR },
  { name: '期待に目を輝かせて', rarity: 820, iconType: MOON },
  { name: '一弓入魂', rarity: 820, iconType: WIND },
  { name: '砂の一昼城', rarity: 820, iconType: MOON },
  { name: '夕闇のMERMAID', rarity: 820, iconType: WAVE },
  { name: 'Dolphinウェイクボード', rarity: 820, iconType: GEAR },
  { name: '黄昏リラクゼーション', rarity: 820, iconType: GEAR },
  { name: 'コタツでぬくぬく', rarity: 820, iconType: SUN },
  { name: 'プレゼント配りのお姉ちゃん', rarity: 820, iconType: SUN },
  { name: '布衣之交', rarity: 820, iconType: WAVE },
  { name: 'コールドテーブル', rarity: 820, iconType: MOON },
  { name: '功夫少女', rarity: 820, iconType: WIND },
  { name: '愛のショコラ', rarity: 820, iconType: GEAR },
  { name: 'コスプレ衣装試着中', rarity: 820, iconType: GEAR },
  { name: 'チャーウーマン', rarity: 820, iconType: WAVE },
  { name: 'トレンド「一日署長」', rarity: 820, iconType: MOON },
  { name: 'ゴールデンタイム', rarity: 820, iconType: WIND },
  { name: '酒！　夢！　コス！', rarity: 820, iconType: MOON },
  { name: 'いつものラーメン屋', rarity: 820, iconType: SUN },
  { name: '走りやすいかも？', rarity: 820, iconType: WAVE },
  { name: '大階段を下って', rarity: 820, iconType: WIND },
  { name: '危険なマッサージ？', rarity: 820, iconType: WAVE },
  { name: '灯台の迎え人', rarity: 820, iconType: MOON },
  { name: 'ねこ×ギャル', rarity: 820, iconType: SUN },
  { name: '刃兼流応援術', rarity: 820, iconType: GEAR },
  { name: '遅刻、遅刻～☆', rarity: 820, iconType: WIND },
  { name: '射撃もお手のもの', rarity: 820, iconType: MOON },
  { name: 'サンタクロースの正体は……', rarity: 820, iconType: WAVE },
];
